apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  namespace: discollama-bat
  name: tracing
spec:
  metric:
    enabled: true
  metrics:
    enabled: true
  tracing:
    otel:
      endpointAddress: alloy-stack-cluster.monitoring.svc.cluster.local:4317
      isSecure: false
      protocol: grpc
    samplingRate: '1'
