apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: comics
  name: comics
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
