apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: books
  name: books
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
