apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: manga
  name: manga
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
