apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: changedetection-data
  name: changedetection-data
  namespace: changedetection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
