apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  namespace: open-webui
spec:
  defaultBackend:
    service:
      name: open-webui
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - ai
