apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui
  namespace: open-webui
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ai.mizar.scalar.cloud`)
      middlewares:
        - name: authentik-auth-proxy
          namespace: default
      priority: 10
      services:
        - name: open-webui
          kind: Service
          namespace: open-webui
          port: http
  tls:
    secretName: open-webui-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui
  namespace: open-webui
spec:
  secretName: open-webui-tls
  dnsNames:
    - "ai.mizar.scalar.cloud"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer