apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: open-webui
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn