apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: open-webui
automountServiceAccountToken: false