kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: open-webui
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: open-webui
      app.kubernetes.io/instance: open-webui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: open-webui
        app.kubernetes.io/instance: open-webui
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: open-webui
      initContainers:
        - name: copy-app-data
          image: ghcr.io/open-webui/open-webui:latest
          command:
            - sh
            - '-c'
            - cp -R -n /app/backend/data/* /tmp/app-data/
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /tmp/app-data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: open-webui-config
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: false
  serviceName: open-webui
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain