apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapr
  namespace: dapr-system
spec:
  defaultBackend:
    service:
      name: dapr-dashboard
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - dapr
