apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: fgc
  name: fgc
  namespace: free-games-claimer-ronin
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi