apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    gethomepage.dev/description: Kubernetes Storage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/icon: longhorn.png
    gethomepage.dev/name: Longhorn
    gethomepage.dev/href: https://longhorn.tahr-toad.ts.net
spec:
  defaultBackend:
    service:
      name: longhorn-frontend
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - longhorn
