apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: plex
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`plex.mizar.scalar.cloud`)
      priority: 10
      services:
        - name: plex-plex-media-server
          kind: Service
          namespace: plex
          port: pms
  tls:
    secretName: plex-pms-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex
  namespace: plex
spec:
  secretName: plex-pms-tls
  dnsNames:
    - "plex.mizar.scalar.cloud"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer