apiVersion: v1
data:
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
    - operator
    jsonPointers:
    - /spec/externalName
  resource.exclusions: |
    - apiGroups:
      - "cilium.io"
      kinds:
      - "CiliumIdentity"
      clusters:
      - "*"
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
