apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: free-games-claimer
  namespace: free-games-claimer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fgc.mizar.scalar.cloud`)
      middlewares:
        - name: home-networks
          namespace: default
      priority: 10
      services:
        - name: free-games-claimer
          kind: Service
          namespace: free-games-claimer
          port: http
  tls:
    secretName: free-games-claimer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: free-games-claimer
  namespace: free-games-claimer
spec:
  secretName: free-games-claimer-tls
  dnsNames:
    - "fgc.mizar.scalar.cloud"
  issuerRef:
    name: le-staging
    kind: ClusterIssuer