kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - role-bindings.yaml
  - service-account.yaml
configMapGenerator:
  - name: homepage
    behavior: create
    files:
      - config/bookmarks.yaml
      - config/custom.css
      - config/custom.js
      - config/docker.yaml
      - config/kubernetes.yaml
      - config/services.yaml
      - config/settings.yaml
      - config/widgets.yaml
