kind: Deployment
apiVersion: apps/v1
metadata:
  name: discollama
  namespace: discollama-bat
  labels:
    app: discollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discollama
  template:
    metadata:
      labels:
        app: discollama
      annotations:
        dapr.io/app-id: prod-discollama
        dapr.io/config: tracing
        dapr.io/enable-api-logging: 'true'
        dapr.io/enabled: 'true'
    spec:
      containers:
        - name: discollama
          image: quay.io/mightydjinn/discollama:v0.2.1
          envFrom:
            - secretRef:
                name: discollama
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
