apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tube-archivist
  namespace: tube-archivist
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tube.mizar.scalar.cloud`)
      middlewares:
        - name: authentik-auth-proxy
          namespace: default
      services:
        - name: tubearchivist
          kind: Service
          namespace: tube-archivist
          port: http
  tls:
    secretName: tube-archivist-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tube-archivist
  namespace: tube-archivist
spec:
  secretName: tube-archivist-tls
  dnsNames:
    - "tube.mizar.scalar.cloud"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer