apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: octobot
  namespace: octobot
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`octobot.mizar.scalar.cloud`)
      middlewares:
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
      priority: 10
      services:
        - name: octobot
          kind: Service
          namespace: octobot
          port: http
  tls:
    secretName: octobot-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: octobot
  namespace: octobot
spec:
  secretName: octobot-tls
  dnsNames:
    - "octobot.mizar.scalar.cloud"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer