kind: Kustomization
resources:
  - install.yaml
  - ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: replace
    envs:
      - config/argocd-cmd-params-cm
patches:
  - path: config/argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
apiVersion: kustomize.config.k8s.io/v1beta1