kind: Kustomization
resources:
  - install.yaml
  - ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: replace
    envs:
      - config/argocd-cmd-params-cm.yaml
apiVersion: kustomize.config.k8s.io/v1beta1