apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: coroot
  namespace: coroot
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`coroot.mizar.scalar.cloud`)
      priority: 10
      services:
        - name: coroot-coroot
          kind: Service
          namespace: coroot
          port: http
  tls:
    secretName: coroot-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coroot
  namespace: coroot
spec:
  secretName: coroot-tls
  dnsNames:
    - "coroot.mizar.scalar.cloud"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
