apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coroot
  namespace: coroot
spec:
  defaultBackend:
    service:
      name: coroot-coroot
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - coroot
