apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: searxng
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`search.scalar.cloud`)
      priority: 10
      services:
        - name: searxng
          kind: Service
          namespace: searxng
          port: http
  tls:
    secretName: searxng-scalar-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng
  namespace: searxng
spec:
  secretName: searxng-scalar-tls
  dnsNames:
    - "search.scalar.cloud"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
