apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: gemma3
  namespace: ollama
spec:
  replicas: 1
  image: gemma3
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 4
      memory: 8Gi
  storageClassName: longhorn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k-w-3
