apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: gemma3
  namespace: ollama
spec:
  replicas: 1
  image: gemma3
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
  storageClassName: local-path
  runtimeClassName: nvidia
  persistentVolumeClaim:
    size: 500Gi

