apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama
  namespace: ollama
spec:
  defaultBackend:
    service:
      name: ollama
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - ollama
