apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama
  namespace: ollama
  annotations:
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    gethomepage.dev/description: Ollama API
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/icon: ollama.png
    gethomepage.dev/name: Ollama
    gethomepage.dev/href: https://ollama.tahr-toad.ts.net
spec:
  defaultBackend:
    service:
      name: ollama-srv-d34b2b
      port:
        name: ollama
  ingressClassName: tailscale
  tls:
    - hosts:
        - ollama
