apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2024.10.5-1
    chart: authentik
    helm:
      values: |
        global:
          envFrom:
            - secretRef:
                name: authentik-global-config
        server:
          volumes:
            - name: authentik-custom-web
              configMap:
                name: authentik-custom-web
          volumeMounts:
            - name: authentik-custom-web
              mountPath: /custom-web
          ingress:
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              cert-manager.io/cluster-issuer: le-prod
            ingressClassName: traefik
            enabled: true
            tls:
            - hosts:
                - authentik.mizar.scalar.cloud
              secretName: authentik-ingress-tls
            hosts:
                - authentik.mizar.scalar.cloud
        postgresql:
          enabled: true
          auth:
            existingSecret: postgresql-config
          primary:
            networkPolicy:
              enabled: false
          readReplicas:
            networkPolicy:
              enabled: false
          backup:
            cronjob:
              networkPolicy:
                enabled: false
        redis:
          enabled: true
          networkPolicy:
            enabled: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
