apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coroot
  namespace: argocd
spec:
  destination:
    namespace: coroot
    server: https://kubernetes.default.svc
  source:
    repoURL: https://coroot.github.io/helm-charts
    targetRevision: 0.3.0
    chart: coroot-ce
    helm:
      values: |
        clickhouse:
          shards: 2
        clickhouse:
          replicas: 2
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
