apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-router
  namespace: argocd
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.26.3
    chart: mc-router
    helm:
      values: |
        minecraft:
          type: LoadBalancer
          port: 25565
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
