apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octobot
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: octobot
    repoURL: https://github.com/mizar-labs/mizar
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true