apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  source:
    path: ollama
    repoURL: https://helm.openwebui.com/
    targetRevision: 6.4.0
    chart: open-webui
    helm:
      releaseName: ollama-stack
      valuesFile: ../helm-values/open-webui.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
