apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 0.8.0
    chart: plex-media-server
    helm:
      releaseName: plex
      values: |
        nameOverride: plex
        image:
          tag: "1.41.4.9463-630c9f557"
        ingress:
          enabled: true
          url: https://plex.tahr-toad.ts.net
          ingressClassName: tailscale
          annotations:
            tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
            tailscale.com/funnel: "true"
        pms:
          configStorage: 100Gi
        resources:
          requests:
            cpu: 4
            memory: 10Gi
        rclone:
          enabled: true
          image:
            tag: "1.69"
          configSecret: "rclone-config"
          remotes:
            - "proton:/plex"
          readOnly: false

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
