apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng-db
  namespace: argocd
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 23.2.5
    chart: redis
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: false
        networkPolicy:
          enabled: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
