apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  source:
    repoURL: https://k8s-home-lab.github.io/helm-charts
    targetRevision: 12.0.0
    chart: tautulli
    helm:
      releaseName: tautulli
      values: |
        image:
          repository: linuxserver/tautulli
          tag: latest
        env:
          TZ: America/Chicago
        persistence:
          config:
            enabled: true
        ingress:
          main:
            enabled: true
            primary: true
            ingressClassName: tailscale
            hosts:
              host: tautulli
            tls:
              - hosts:
                  - tautulli
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
