apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mizar-labs/mizar
    path: tautulli
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tautulli
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
