apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-chrome.yaml
  - deployment-meilisearch.yaml
  - deployment-web.yaml
  - namespace.yaml
  - pvc-data.yaml
  - pvc-meilisearch.yaml
  - service-chrome.yaml
  - service-meilisearch.yaml
