- Cluster:
  - Load Balancer:
      href: https://traefik.tahr-toad.ts.net
      description: Traefik Dashboard
      widget:
        type: traefik
        url: https://traefik.tahr-toad.ts.net

- Global:
  - NextDNS:
      href: https://my.nextdns.io/
      description: DNS Management
      widget:
        type: nextdns
        profile: {{HOMEPAGE_VAR_NEXTDNS_PROFILE_MAIN}}
        key: {{HOMEPAGE_VAR_NEXTDNS_KEY}}


- My Third Group:
  - My Third Service:
      href: http://localhost/
      description: Homepage is 😎
