- Cluster:
  - Load Balancer:
      href: https://traefik.tahr-toad.ts.net
      description: Traefik Dashboard
      widget:
        type: traefik
        url: https://traefik.tahr-toad.ts.net
  - ArgoCD:
      href: https://argocd.tahr-toad.ts.net
      description: ArgoCD Dashboard
      widget:
        type: argocd
        url: http://argocd.host.or.ip:port
        key: {{HOMEPAGE_VAR_ARGOCD_KEY}}

- Global:
  - NextDNS:
      href: https://my.nextdns.io/
      description: DNS Management
      widget:
        type: nextdns
        profile: {{HOMEPAGE_VAR_NEXTDNS_PROFILE_MAIN}}
        key: {{HOMEPAGE_VAR_NEXTDNS_KEY}}
  - Unifi:
      href: https://udm.tahr-toad.ts.net
      description: Unifi Controller
      widget:
        type: unifi
        url: https://udm.tahr-toad.ts.net
        username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
  - Traefik:
      href: https://traefik.tahr-toad.ts.net
      description: Traefik Dashboard
      widget:
        type: traefik
        url: https://traefik.tahr-toad.ts.net


- My Third Group:
  - My Third Service:
      href: http://localhost/
      description: Homepage is 😎
