- My First Group:
  - AI Service:
      href: https://traefik.tahr-toad.ts.net
      description: Traefik Dashboard
      widget:
        type: traefik
        url: https://traefik.tahr-toad.ts.net

- My Second Group:
  - My Second Service:
      href: http://localhost/
      description: Homepage is the best

- My Third Group:
  - My Third Service:
      href: http://localhost/
      description: Homepage is 😎
