- Home:
  - Calendar:
      widget:
        type: calendar
        firstDayInWeek: sunday # optional - defaults to monday
        view: monthly # optional - possible values monthly, agenda
        maxEvents: 10 # optional - defaults to 10
        showTime: true # optional - show time for event happening today - defaults to false
        timezone: America/Chicago # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
        integrations: # optional
          - type: ical # Show calendar events from another service
            url: {{HOMEPAGE_VAR_ICAL_URL}} # required - url to ical file
            name: My Events # required - name for these calendar events
            color: zinc # optional - defaults to pre-defined color for the service (zinc for ical)
            params: # optional - additional params for the service
              showName: true # optional - show name before event title in event line - defaults to false

- Operation:
  - Proxmox:
      href: https://pve.tahr-toad.ts.net:8006
      icon: proxmox.png
      widget:
        type: proxmox
        url: https://pve.tahr-toad.ts.net:8006
        username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
        password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
        node: pve-1 # optional
  - ArgoCD:
      href: https://argocd.tahr-toad.ts.net
      icon: argo-cd.png
      description: ArgoCD Dashboard
      widget:
        type: argocd
        url: https://argocd.tahr-toad.ts.net
        key: {{HOMEPAGE_VAR_ARGOCD_KEY}}
  - Traefik:
      href: https://traefik.tahr-toad.ts.net
      icon: traefik.png
      description: Traefik Dashboard
      widget:
        type: traefik
        url: https://traefik.tahr-toad.ts.net
  - Unifi:
      href: https://udm.tahr-toad.ts.net
      icon: unifi.png
      description: Unifi Controller
      widget:
        type: unifi
        url: https://udm.tahr-toad.ts.net
        username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
  - NextDNS:
      href: https://my.nextdns.io/
      icon: nextdns.png
      description: DNS Management
      widget:
        type: nextdns
        profile: {{HOMEPAGE_VAR_NEXTDNS_PROFILE_MAIN}}
        key: {{HOMEPAGE_VAR_NEXTDNS_KEY}}


