providers:
  finnhub: {{HOMEPAGE_VAR_FINNHUB_API_KEY}}
  hdhomerun: {{HOMEPAGE_VAR_HDHOMERUN_URL}}
  plex: {{HOMEPAGE_VAR_PLEX_TOKEN}}
  longhorn:
    url: https://longhorn.tahr-toad.ts.net
layout:
  DNS:
    style: row
    columns: 3