- datetime:
    text_size: xl
    format:
      timeStyle: long
      dateStyle: long
- openmeteo:
    label: Bryan # optional
    latitude: 30.677446
    longitude: -96.330783
    timezone: America/Chicago # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- resources:
  backend: resources
  expanded: true
  cpu: true
  memory: true
  network: default
- longhorn:
    # Show the expanded view
    expanded: true
    # Shows a node representing the aggregate values
    total: true
    # Shows the node names as labels
    labels: true
    # Show the nodes
    nodes: true

- search:
    provider: duckduckgo
    target: _blank
- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
      - VSAT
      - GSAT
      - SNDL
      - GME
      - AMC
      - NVDA
