- longhorn:
    expanded: true
    total: true
    labels: true
    nodes: true


- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- search:
    provider: custom
    url: https://search.tahr-toad.ts.net/search?q=
    target: _blank
    #suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q= # Optional
    #showSearchSuggestions: true # Optional

- openweathermap:
    label: Bryan
    latitude: 30.677446
    longitude: -96.330783
    units: imperial
    apiKey: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- datetime:
    text_size: xl
    format:
      timeStyle: long
      dateStyle: long

- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
      - VSAT
      - GSAT
      - SNDL
      - GME
      - AMC
      - NVDA