apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -n crypto
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: octobot
  name: octobot
  namespace: crypto
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5001
  selector:
    io.kompose.service: octobot
