apiVersion: apps/v1
kind: Deployment
metadata:
  name: octobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octobot
  template:
    metadata:
      labels:
        app: octobot
    spec:
      containers:
        - name: octobot
          image: drakkarsoftware/octobot:stable

          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "4Gi"
          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /octobot/logs
              name: logs
            - mountPath: /octobot/backtesting
              name: backtesting
            - mountPath: /octobot/tentacles
              name: tentacles
            - mountPath: /octobot/user
              name: user
      volumes:
        - name: logs
          emptyDir: {}
        - name: backtesting
          persistentVolumeClaim:
            claimName: octobot-backtesting
        - name: tentacles
          emptyDir:
            sizeLimit: 2000Mi
        - name: user
          persistentVolumeClaim:
            claimName: octobot-user
