apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: octobot-claim2
  name: octobot-claim2
  namespace: crypto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
