apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance
  namespace: glance
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`glance.mizar.scalar.cloud`)
      priority: 10
      services:
        - name: glance
          kind: Service
          namespace: glance
          port: http
  tls:
    secretName: glance-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance
  namespace: glance
spec:
  secretName: glance-tls
  dnsNames:
    - "glance.mizar.scalar.cloud"
  issuerRef:
    name: le-staging
    kind: ClusterIssuer