kind: Kustomization
namespace: searxng
resources:
  - searxng-deployment.yaml
  - searxng-namespace.yaml
  - searxng-service.yaml
  - ingress.yaml
configMapGenerator:
  - name: searxng-config
    files:
      - config/settings.yml
  - name: searxng-limiter-config
    files:
      - config/limiter.toml
  - name: searxng-tune
    literals:
      - UWSGI_THREADS=4
      - UWSGI_WORKERS=4
apiVersion: kustomize.config.k8s.io/v1beta1
