kind: Kustomization
resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - searxng-claim0-persistentvolumeclaim.yaml
  - searxng-deployment.yaml
  - searxng-namespace.yaml
  - searxng-service.yaml
  - valkey-data2-persistentvolumeclaim.yaml
configMapGenerator:
  - name: searxng-config
    files:
      - config/settings.yml
  - name: searxng-limiter-config
    files:
      - config/limiter.toml
apiVersion: kustomize.config.k8s.io/v1beta1