apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: searxng
  name: searxng
  namespace: searxng
spec:
  ports:
    - name: http
      port: 8080
      targetPort: web
  selector:
    app.kubernetes.io/name: searxng
