apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: searxng
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: searxng
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: searxng
    spec:
      containers:
        - env:
            - name: SEARXNG_BASE_URL
              value: https://search.tahr-toad.ts.net/
            - name: UWSGI_THREADS
              value: "4"
            - name: UWSGI_WORKERS
              value: "4"
          image: docker.io/searxng/searxng:latest
          name: searxng
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - ALL
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-claim0
      restartPolicy: Always
      volumes:
        - name: searxng-claim0
          persistentVolumeClaim:
            claimName: searxng-claim0
